version: "3.8"
networks:
  test-mysql-net:
    name: test-mysql-network

services:
  test-mysql1:
    image: mysql:8.0
    hostname: test-mysql1
    restart: none
    environment:
      MYSQL_ROOT_PASSWORD: mysql06
    networks:
      - test-mysql-net
    command: --default-authentication-plugin=mysql_native_password

  test-mysql2:
    image: mysql:8.0
    hostname: test-mysql2
    restart: none
    environment:
      MYSQL_ROOT_PASSWORD: mysql06
    networks:
      - test-mysql-net
    command: --default-authentication-plugin=mysql_native_password
